---
name: MKTXP
version: dev
slug: mikrotik-exporter
description: Mikrotik Exporter
url: https://github.com/plazari15
startup: services
ingress: true
ingrss_port: 49090
ingress_stream: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: once
advanced: true
hassio_api: true
host_network: true