global:
  scrape_interval: 15s  # Define o intervalo de coleta de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Alvo para o próprio Prometheus

  - job_name: 'mikrotik-exporter'
    static_configs:
      - targets: ['192.168.88.176:49090']  # Substitua pelo endereço do seu aplicativo e porta de métricas

  - job_name: 'homeassistant'
    metrics_path: "/api/prometheus"
    static_configs:
      - targets: ['192.168.88.176:8123']

   # Adicione mais blocos 'job_name' conforme necessário para monitorar outros serviços ou aplicativos
